### PR TITLE
Feature 1333

### PR DESCRIPTION
**Pull request by nmarkovic04**
Includes new UI and the multiple clientIDs URL parameters fix.

### CODE REVIEW

**Comment by rubikzube** [comment]
This PR hasn't updated the display of search suggestions, can't be merged until that happens

**Comment by nmarkovic04** [comment]
@rubikzube Yeah, don't merge yet. I'm still waiting for error screen design from Arthur.

**Comment by rubikzube** [comment]
I am uncertain why the following tests changed to multiple tests with one test per assertion instead of one test with multiple assertions.
```
testTrackACClickBuilder_sectionNameSpecified_selectType > now 7 tests with one assertion each
testTrackACClickBuilder_withNoSectionName_selectType > now 7 tests with one assertion each
testTrackConversionBuilder_onlySearchTerm > now 4 tests with one assertion each
testTrackConversionBuilder_withItemName > now 4 tests with one assertion each
testTrackConversionBuilder_withSectionName > now 4 tests with one assertion each
testTrackConversionBuilder_withRevenue > now 5 tests with one assertion each
testTrackConversionBuilder_AllFields > now 7 tests with one assertion each
```

**Comment by nmarkovic04** [comment]
@rubikzube Because having multiple assertions in any test mean that multiple statements are tested. A better TDD approach is to a single (or as less as possible) assertion per test case.

**Comment by rubikzube** [comment]
I agree with the general principle but I'm not sure that applies in this
case.  The functionality under test is translating a given set of function
parameters into a URL.  If the function parameters are the exact same for a
group of tests, and each test only looks at a a tiny part of the URL, it's
bloats the tests and makes the overall test harder to understand and read,
because of the extra ten of lines of boilerplate per test.

**Pull request merged**
