### PR TITLE
[CSL-2828] Add filter_by to Variations Map Builder

### PR DESCRIPTION
**Pull request by Mudaafi**

### CODE REVIEW

**Comment by crgee1** [comment]
@Mudaafi IMO filter_by is very similar to pre_filter_expressions so I'd want the implementations to be similar. So I would think it might be more consistent to implement it as a string like in [here](https://github.com/Constructor-io/constructorio-client-swift/pull/185). Thoughts?

**Comment by Mudaafi** [comment]
@crgee1 Ooh you're right, I'm aligned with keeping it in the same format as how we do for `preFilterExpressions`. Should I keep the current object implementation and overload one that takes in a string or should I only do a string one to avoid confusion? I'm cool with either.

**Comment by crgee1** [comment]
For record keeping purposes, we agreed to have both implementations and overload accordingly

**Review by jjl014 — APPROVED** [review]
This LGTM! 🚀 Thanks!

We'll need to revisit the testing issue on Xcode 15+, I'll create a story for us to keep track of it.

**Pull request merged**
